extends Resource
class_name SoundEffect

enum SOUND_EFFECT_TYPE{
	ON_BUTTON_CLICKED,
	NOTIFICATION,
	ON_NOTE_CLICKED,
	PHONE_MESSAGE_RECEIVE,
	UI_COMBO_DOWN,
	UI_COMBO_UP_BIG,
	UI_COMBO_UP_SMALL,
	UI_LIFE_LOST,
	UI_CLOSE_PAUSEMENU,
	UI_MOUSEHOVER_PAUSEMENU,
	UI_OPEN_PAUSEMENU,
	UI_SELECT_PAUSEMENU,
	UI_MOUSEHOVER_PHONEMENU,
	UI_OPEN_PHONEMENU,
	UI_SELECT_PHONEMENU,
	OBJ_PHONE_MESSAGE_RECEIVE,
	OBJ_PHONE_MESSAGE_SEND,
	OBJ_PHONE_NOTIFICATION,
	OBJ_PHONE_TYPING_01,
	OBJ_PHONE_TYPING_02,
	OBJ_PHONE_TYPING_03,
	OBJ_PHONE_TYPING_04
}

@export var type : SOUND_EFFECT_TYPE
@export var sound_effect : AudioStreamWAV
@export_range(-40,20) var volume = 0
